- javaClub/team3/Main.java
- javaClub/team3/Task5.java
> Main class modified

- Java-Club-2.iml
- javaClub/team3/Main.java
- javaClub/team3/Task10.java
- javaClub/team3/Task11.java
- javaClub/team3/Task2.java
- javaClub/team3/Task4.java
- javaClub/team3/Task7.java
- javaClub/team3/Task9.java
> Task2 7 11

- src/com/softserve/academy/basic/MainBasic.java
- src/com/softserve/academy/basic/Task9.java
- test/basic/Task9Test.java
> Add task 9

- src/com/softserve/academy/basic/MainBasic.java
- src/com/softserve/academy/basic/Task9.java
- src/com/softserve/academy/string/MainString.java
- src/com/softserve/academy/string/Task59.java
- test/string/Task59Test.java
> Add task 59 and some input fix

- src/com/softserve/academy/string/MainString.java
- src/com/softserve/academy/string/Task57.java
- test/string/Task57Test.java
> Add task 57

- tasks/Main.java
- tasks/Task8.java
> added task8 and edited Main

- src/com/softserve/academy/string/MainString.java
- src/com/softserve/academy/string/Task67.java
- test/string/Task67Test.java
> Add task 67

- src/com/softserve/academy/opp/MainOPP.java
- src/com/softserve/academy/opp/Task3.java
- test/OPP/Task3Test.java
> Add task 49

- src/com/softserve/academy/classes/MainClasses.java
- src/com/softserve/academy/classes/Task7.java
- test/classes/Task7Test.java
> Add task 18

- src/com/softserve/academy/classes/MainClasses.java
- src/com/softserve/academy/classes/Task13.java
- test/classes/Task13Test.java
> Add task 24

- src/com/softserve/academy/classes/MainClasses.java
- src/com/softserve/academy/classes/Task8.java
- test/classes/Task8Test.java
> Add task 19

- javaClub/team3/Main.java
- javaClub/team3/Task.java
- javaClub/team3/Task11.java
- javaClub/team3/Task2.java
- javaClub/team3/Task7.java
Updated tasks 2, 7, 11.
Added Scanner to Task.java
"Fix" warning in Main.java
> Team3 krip4yk

- tasks/Task9.java
> Added Task 9

- README.md
- Tasks/task3.java
`package Tasks.Task3;
import java.util.Scanner;
public class task3 {
public static double main (){
Scanner scanner = new Scanner(System.in);
System.out.println("This program calculate the volume of a cuboid with three values: length, width, height");
System.out.print("Enter value for length : ");
double length = scanner.nextDouble();
System.out.print("Enter value for width : ");
double width = scanner.nextDouble();
System.out.print("Enter value for height : ");
double height = scanner.nextDouble();
getVolumeOfCuboid(length,width,height);
String answer = "Volueme of cuboid is : ";
System.out.println(answer + getVolumeOfCuboid(length,width,height));
return 0;
}
public static double getVolumeOfCuboid(final double length, final double width, final double height) {
double volume = length * …
> Team2_task3

- src/tasks/ApplMain.java
- src/tasks/Task2.java
> team2task2.java

- src/tasks/ApplMain.java
- src/tasks/Task12.java
- src/tasks/Task4.java
> Team2task4

- tasks/Task5.java
Modified Task 5: added input verification
> Modified Task 5

- javaClub/team3/Main.java
For using just uncommit (ctrl+/) line
> Added commented methods calls to Main.java

- src/tasks/ApplMain.java
- src/tasks/Task22.java
> team2task22

- src/tasks/ApplMain.java
- src/tasks/Task18.java
> team2task18

- tests/Task5Test.java
> added test for T5

- .classpath
- src/tasks/Task10.java
- src/tasks/Task18.java
- src/tasks/Task2.java
- src/tasks/Task22.java
- src/tasks/Task3.java
- tst/tests/Task3Test.java
> team2test3

- javaClub/team3/Main.java
(same as 11, so it's an easy way to resolve)
> Task 62 added

- javaClub/team3/Task52.java
- javaClub/team3/Task57.java
> Task52-57 update

- .classpath
- src/tasks/Task7.java
- tst/tasks/Task7Test.java
> Team2Test7

- Library/src/SCRIPTS/PATCH_V1/PK_incremet_Patch.sql
- Library/src/SCRIPTS/PATCH_V1/README.txt
- Library/src/SCRIPTS/PATCH_V1/requests_fix_Patch.sql
Change all PK (id): add auto_increment
Change requests table: change book_id FK to book_copy_id FK (in request to get book by book_id - program will give any available book_copy_id by book_id)
> Patch V1 UPDATED
